project:
  type: website
  
execute:
  freeze: auto

website:
  title: "IfyE Data Talks"
  navbar:
    right:
      - text: "Webinar"
        file: webinar.qmd
      - text: "Prerequisites"
        file: prerequisites.qmd
      - icon: github
        href: https://github.com/symplyelah/symplyelah.github.io
  page-footer: "All material is shared under the [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/){target='_blank'} license."
  
format:
  html:
    theme: 
      light: forwards-light.scss
      dark: forwards-dark.scss
    highlight-style: forwards.theme
    toc: true
    link-external-newwindow: true
    