---
title: "Bridging Data and Decision-Making: Data Visualization Techniques with R"
subtitle: "IEEE Nigeria Southeast Subsection"
description: Webinar Presentation
author: Ifeoma Egbogah
---

# Webinar Overview

In today’s world, data is everywhere—but data alone doesn’t drive decisions. Communicating data through clear, purposeful, and accessible visualisations is an essential skill for anyone working with data—whether you're a scientist, analyst, researcher, or manager. When well-crafted, the insights we extract and how clearly we communicate them truly make an impact. However, poor design choices can hinder understanding or, worse, mislead the audience—intentionally or not.

# Join

[Google Meet](https:/meet.google.com/jyn-ftyj-cdz){.btn .btn-primary target="_blank"}

------------------------------------------------------------------------

📆  August 2, 2025

⏰ 12:00PM

[🏨  Google Meet](https:/meet.google.com/jyn-ftyj-cdz)

------------------------------------------------------------------------



## Is this webinar for me?

This webinar is ideal for you if you:

-   want to master the art of presenting data through clear, impactful visualizations;

-   are looking to enhance your design skills to create visuals that are both effective and informative; and

-   are ready to invest time in selecting the right chart types, color schemes, fonts, and other elements that guide your audience and amplify your message.

# Slides

Here's a link to the [slides](/slides/index.html){target="_blank"} in a new window.

Here are the slides embedded:

<iframe class="slide-deck ar16x9" src="/slides/index.html" title="slides">

</iframe>

# Citations and data

## R packages

Thank you to developers, sharers, teachers, and the entire R community for building things and creating resources to help us all learn.

-   `tidyverse`: Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, https://doi.org/10.21105/joss.01686
-   `ggplot2`: H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.
-   `ggrepel`: Kamil Slowikowski (2021). ggrepel: Automatically Position Non-Overlapping Text Labels with 'ggplot2'. R package version 0.9.1. https://github.com/slowkow/ggrepel
-   `janitor`:Sam Firke (2021). janitor: Simple Tools for Examining and Cleaning Dirty Data. R package version 2.1.0. https://github.com/sfirke/janitor
