---
title: Bridging Data and Decision-Making: Data Visualization Techniques with R
subtitle: "Nnamdi Azikwe University"
description: Webinar Presentation
author: Ifeoma Egbogah
draft: false
---

# Slides

Here's a link to the [slides](/slides/index.qmd){target="_blank"} in a new window.

Here are the slides embedded:

<iframe class="slide-deck ar16x9" src="/slides/index.html" title="Presentation slides">

</iframe>

# Citations and data

## R packages

Thank you to developers, sharers, teachers, and the entire R community for building things and creating resources to help us all learn.

-   `tidyverse`: Wickham et al., (2019). Welcome to the tidyverse. Journal of Open Source Software, 4(43), 1686, https://doi.org/10.21105/joss.01686
-   `ggplot2`: H. Wickham. ggplot2: Elegant Graphics for Data Analysis. Springer-Verlag New York, 2016.
-   `ggrepel`: Kamil Slowikowski (2021). ggrepel: Automatically Position Non-Overlapping Text Labels with 'ggplot2'. R package version 0.9.1. https://github.com/slowkow/ggrepel
-   `gghighlight`: Hiroaki Yutani (2020). gghighlight: Highlight Lines and Points in 'ggplot2'. R package version 0.3.1. https://github.com/yutannihilation/gghighlight/
-   `R Markdown`: Yihui Xie and J.J. Allaire and Garrett Grolemund (2018). R Markdown: The Definitive Guide. Chapman and Hall/CRC. ISBN 9781138359338. URL https://bookdown.org/yihui/rmarkdown.
-   `sf`: Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal 10 (1), 439-446, https://doi.org/10.32614/RJ-2018-009
-   `paletteer`: See AUTHORS file. (2021). paletteer: Comprehensive Collection of Color Palettes. R package version 1.3.0. https://github.com/EmilHvitfeldt/paletteer
-   `gapminder`: Jennifer Bryan (2017). gapminder: Data from Gapminder. https://github.com/jennybc/gapminder, http://www.gapminder.org/data/, https://doi.org/10.5281/zenodo.594018.
-   `janitor`:Sam Firke (2021). janitor: Simple Tools for Examining and Cleaning Dirty Data. R package version 2.1.0. https://github.com/sfirke/janitor
